config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links, only: [:index, :create, :show, :destroy, :update], module: "links"
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, :url => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8, message: "must have a minimum of 8 characters"}
  validates :password_confirmation, presence: true

  has_many :links
end

app/controllers/api/v1/links/links_controller.rb
class Api::V1::Links::LinksController < ApplicationController
  respond_to :json

  def index
    respond_with current_user.links
  end

  def update
    @link = Link.update(params[:id], link_params)
    respond_with @link, json: @link
  end

  private

    def link_params
      params.require(:link).permit(:title, :url, :user_id, :read_status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id

    if @link.save
      redirect_to links_path
    else
      flash.now[:errors]
      redirect_to links_path
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :user_id, :read_status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:login][:email])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:errors] = "Invalid Login"
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="row">
      <form class="col s2">
        <div class="input">
          <input placeholder="Search" id="search" type="search" required>
          <label for="search-query"></label>
        </div>
      </form>
      <% if current_user %>
        Welcome
        <%= link_to "Logout", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Login", login_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtboxAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="container">
  <div class="row">
    <div class="column center">
      <h2>ThoughtBox Assessment</h2>
    </div>
    <div>
      <h4>Add a New Link</h4>
      <%= form_for(:link) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :url %>
        <%= f.text_field :url %>
        <%= f.submit "Create Link" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div id="sort-alphabetical" class="btn">Sort A-Z</div>
    <div id="read" class="btn">Marked as Read</div>
    <div id="unread" class="btn">Marked as Unread</div>
  </div>
  <div id="links-list"></div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s8 center">
      <h3>Create a new account</h3>

      <%= form_for(@user) do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password, help: "Must be 8 Characters" %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create Account" %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= link_to "Sign Up", new_user_path %>